# Generated by Django 2.0.13 on 2019-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='date')),
                ('open', models.FloatField(verbose_name='open')),
                ('close', models.FloatField(verbose_name='close')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('vol', models.IntegerField(verbose_name='vol')),
                ('stockCode', models.CharField(max_length=10, verbose_name='stockCode')),
            ],
            options={
                'db_table': 'stockInfo',
            },
        ),
    ]
