"""
Django settings for MyDjangoOBVProj project.

Generated by 'django-admin startproject' using Django 2.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x8mnhp$vq)6y(9a&8!rv49q!t)$l&24575f4rv)e1d6cans*8a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MyDjangoOBVProj',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyDjangoOBVProj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyDjangoOBVProj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql', # 数据库引擎
         'NAME': 'djangoStock',                # 数据库名
         'USER': 'root',                       # 用户名
         'PASSWORD': '123456',                 # 密码
         'HOST': 'localhost',                  # 主机名
         'PORT': '3306',                       # 端口号
         'OPTIONS':{'isolation_level':None}
     }
 }


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # 定义格式
    'formatters': {
        # 复杂的打印格式                    
        'myFormat': {
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(levelname)s] %(message)s'
        },                  
        # 简单的打印格式 
        'mySimpleFormat': { 
            'format': '[%(asctime)s][%(levelname)s] %(message)s'
        },           
    },
    # 定义过滤器
    'filters': {
        # 可以输出debug格式日志         
        'enableDebug': {                                
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'disableDebug': {                                
            '()': 'django.utils.log.RequireDebugFalse',
        }        
    },
    'handlers': {
        'console':{
            'level':'DEBUG',
            # debug级别日志输出到控制台
            'filters': ['enableDebug'],  
            'class':'logging.StreamHandler',
            'formatter': 'mySimpleFormat'
        },
        'default': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log/myLog.log'),
            'formatter': 'myFormat'
        },
        # 针对DEBUG级别的日志
        'debug': {
            'level': 'DEBUG',
            'filters': ['enableDebug'],
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log/error.log'),            
            'formatter': 'myFormat'
        },
        # 针对ERROR级别的日志
        'error': {
            'level': 'ERROR',
            'filters': ['disableDebug'],
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log/error.log'),
            'formatter': 'myFormat'
        }
    },
    'loggers': {
        '': {
            'handlers': ['console', 'default','error'],
            'level': 'DEBUG'
        }
    },
}